packages:
  - packages/*
  - examples/*

catalog:
  "@biomejs/biome": ^2.5.1
  "@effect/vitest": ^0.29.0
  "@types/node": ^24.1.0
  effect: ^3.21.4
  globals: ^17.7.0
  npm-check-updates: ^22.2.7
  publint: ^0.3.21
  rimraf: ^6.1.3
  sort-package-json: ^4.0.0
  tsx: ^4.22.4
  typescript: ^6.0.3
  typedoc: ^0.28.19
  typedoc-plugin-markdown: ^4.12.0
  vitest: ^4.1.9

overrides:
  cookie@<0.7.0: ^0.7.0
  esbuild@<=0.24.2: ^0.24.3
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  ts-deepmerge@<8.0.0: ^8.0.0
  typebox: 1.2.19
  vitest: "catalog:"

linkWorkspacePackages: true
preferWorkspacePackages: true
injectWorkspacePackages: true

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msgpackr-extract: true

minimumReleaseAge: 1440
