{
  "packages": [
    "packages/*"
  ],
  "catalog": {
    "@biomejs/biome": "^2.3.13",
    "@effect/platform": "^0.94.2",
    "@effect/platform-node": "^0.104.1",
    "@types/node": "25.1.0",
    "effect": "3.19.15",
    "globals": "^17.2.0",
    "npm-check-updates": "^19.3.2",
    "publint": "0.3.17",
    "rimraf": "^6.1.2",
    "tsx": "4.21.0",
    "typescript": "^5.9.3"
  },
  "onlyBuiltDependencies": [
    "@parcel/watcher",
    "esbuild",
    "msgpackr-extract"
  ]
}