{
  "packages": [ "packages/*", "examples/*" ],
  "catalog":
    {
      "@biomejs/biome": "^2.4.8",
      "@types/node": "25.5.0",
      "effect": "3.20.0",
      "globals": "^17.4.0",
      "npm-check-updates": "^19.6.5",
      "publint": "0.3.18",
      "rimraf": "^6.1.3",
      "tsx": "4.21.0",
      "typescript": "^5.9.3"
    },
  "onlyBuiltDependencies": [ "@parcel/watcher", "esbuild", "msgpackr-extract" ]
}
