packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.11
  '@effect/platform': ^0.94.1
  '@effect/platform-node': ^0.104.0
  '@types/node': 25.0.9
  effect: 3.19.14
  globals: ^17.0.0
  npm-check-updates: ^19.3.1
  publint: 0.3.17
  rimraf: ^6.1.2
  tsx: 4.21.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract
