packages:
  - packages/*

catalog:
  '@effect/platform': ^0.93.6
  '@effect/platform-node': ^0.103.0
  '@eslint/compat': ^2.0.0
  '@eslint/js': ^9.39.1
  '@types/node': 24.10.1
  effect: 3.19.8
  eslint: ^9.39.1
  globals: ^16.5.0
  npm-check-updates: 19.1.2
  prettier: ^3.7.4
  publint: 0.3.15
  rimraf: ^6.1.2
  tsx: 4.21.0
  typescript: ^5.9.3
  typescript-eslint: ^8.48.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract
