<div
  class="
  py-3
  flex
  items-center
  text-xs
  text-base-400
  uppercase
  before:flex-1
  before:border-t
  before:border-base-200
  before:me-6
  after:flex-1
  after:border-t
  after:border-base-200
  after:ms-6
  dark:text-base-500
  dark:before:border-gray-600
  dark:after:border-gray-600">
  <slot>Or</slot>
</div>
