import { render } from 'svelte/server';
import type { EmailMessage } from './types';
import EmailChanged from './EmailChanged.svelte';
import { sendEmail } from './fake';

export const sendMailboxVerificationEmail = sendEmail;

/**
 * The mailbox verification emails are generated by Passlock
 * but we need to render our own "Your account email was changed"
 * email. This is a basic example using the {@link render} helper.
 * @param param0
 */
export const sendEmailUpdatedNotification = async ({
	givenName,
	email
}: {
	givenName: string;
	email: string;
}) => {
	const renderedEmailHtml = render(EmailChanged, { props: { givenName } });
	const html = `<html><body>${renderedEmailHtml.body}</body></html>`;
	const text = `Dear ${givenName}, the email address associated with your account was recently changed. If you did not make this change, please contact us immediately.`;

	const emailMessage: EmailMessage = {
		recipientEmail: email,
		subject: 'Your account email was changed',
		body: {
			html,
			text
		}
	};

	sendEmail(emailMessage);
};
