<div
  class="
    py-3
    flex
    items-center
    text-xs
    text-gray-400
    uppercase
    before:flex-1
    before:border-t
    before:border-primary-200
    before:me-6
    after:flex-1
    after:border-t
    after:border-primary-200
    after:ms-6">
  <slot>Or</slot>
</div>
